# -*- coding: utf-8 -*-
"""Global_landslide_Catalog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rO71oVHolzdkTI4_617dMztQHbV6pKR-

# Landslide Data Analysis and Visualization

This notebook analyzes and visualizes global landslide data, with a specific focus on New Zealand and the Auckland region, using the provided CSV file and `matplotlib` for static visualizations.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install cartopy

import pandas as pd
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

# --- 1. Load and Inspect Data ---
# Load the CSV file into a pandas DataFrame
df = pd.read_csv('/content/Global_Landslide_Catalog_Export_rows.csv')

# --- 2. Prepare Data for Mapping ---
# Create a new DataFrame with only latitude and longitude columns
df_mapping = df[['latitude', 'longitude']].copy()

# Remove rows with missing or invalid latitude or longitude values
df_mapping.dropna(subset=['latitude', 'longitude'], inplace=True)
df_mapping = df_mapping[(df_mapping['latitude'] >= -90) & (df_mapping['latitude'] <= 90)]
df_mapping = df_mapping[(df_mapping['longitude'] >= -180) & (df_mapping['longitude'] <= 180)]

# --- 3. Visualize Global Landslides (Static) ---
fig_global = plt.figure(figsize=(12, 8))
ax_global = fig_global.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
ax_global.add_feature(cfeature.COASTLINE)
ax_global.add_feature(cfeature.BORDERS)
ax_global.scatter(df_mapping['longitude'], df_mapping['latitude'], color='red', s=1, alpha=0.5)
ax_global.set_extent([-180, 180, -90, 90], crs=ccrs.PlateCarree())
ax_global.set_title('Global Distribution of Landslides')
fig_global.text(0.5, 0.01, f"Figure 1: Global distribution of {len(df_mapping)} landslides based on latitude and longitude data.", wrap=True, horizontalalignment='center', fontsize=10)
plt.savefig("global_landslide_map_static.png", dpi=600, bbox_inches='tight')
plt.close(fig_global) # Close the figure to free memory

print("Static global landslide map saved as global_landslide_map_static.png")

# --- 4. Filter Data for New Zealand ---
df_new_zealand = df[df['country_code'] == 'NZ'].copy()
print(f"\nNumber of landslides found in New Zealand: {len(df_new_zealand)}")

# --- 5. Visualize landslides in New Zealand (Static) ---
fig_nz = plt.figure(figsize=(8, 10))
ax_nz = fig_nz.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
ax_nz.add_feature(cfeature.LAND)
ax_nz.add_feature(cfeature.OCEAN)
ax_nz.add_feature(cfeature.COASTLINE)
ax_nz.add_feature(cfeature.BORDERS, linestyle=':')
ax_nz.scatter(df_new_zealand['longitude'], df_new_zealand['latitude'], color='green', s=10, alpha=0.7)
nz_bbox = {
    'min_latitude': -48.0,
    'max_latitude': -33.0,
    'min_longitude': 166.0,
    'max_longitude': 178.0
}
ax_nz.set_extent([nz_bbox['min_longitude'], nz_bbox['max_longitude'],
               nz_bbox['min_latitude'], nz_bbox['max_latitude']],
              crs=ccrs.PlateCarree())
ax_nz.gridlines(draw_labels=True, linewidth=1, color='gray', alpha=0.5, linestyle='--')
ax_nz.set_title('Landslide Distribution in New Zealand')
fig_nz.text(0.5, 0.01, f"Figure 2: Distribution of {len(df_new_zealand)} landslides within New Zealand.", wrap=True, horizontalalignment='center', fontsize=10)
plt.savefig("new_zealand_landslide_map_static.png", dpi=600, bbox_inches='tight')
plt.close(fig_nz) # Close the figure

print("Static New Zealand landslide map saved as new_zealand_landslide_map_static.png")


# --- 6. Filter data for Auckland, New Zealand ---
auckland_bbox = {
    'min_latitude': -37.5,
    'max_latitude': -36.0,
    'min_longitude': 174.0,
    'max_longitude': 175.5
}
df_auckland = df_mapping[
    (df_mapping['latitude'] >= auckland_bbox['min_latitude']) &
    (df_mapping['latitude'] <= auckland_bbox['max_latitude']) &
    (df_mapping['longitude'] >= auckland_bbox['min_longitude']) &
    (df_mapping['longitude'] <= auckland_bbox['max_longitude'])
].copy()
print(f"\nNumber of landslides found in the Auckland region: {len(df_auckland)}")

# --- 7. Visualize landslides in Auckland (Static) ---
fig_auckland = plt.figure(figsize=(8, 8))
ax_auckland = fig_auckland.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
ax_auckland.add_feature(cfeature.LAND)
ax_auckland.add_feature(cfeature.OCEAN)
ax_auckland.add_feature(cfeature.COASTLINE)
ax_auckland.add_feature(cfeature.BORDERS, linestyle=':')
ax_auckland.scatter(df_auckland['longitude'], df_auckland['latitude'], color='blue', s=10, alpha=0.7)
ax_auckland.set_extent([auckland_bbox['min_longitude'], auckland_bbox['max_longitude'],
               auckland_bbox['min_latitude'], auckland_bbox['max_latitude']],
              crs=ccrs.PlateCarree())
ax_auckland.gridlines(draw_labels=True, linewidth=1, color='gray', alpha=0.5, linestyle='--')
ax_auckland.set_title('Landslide Distribution in Auckland, New Zealand')
fig_auckland.text(0.5, 0.01, f"Figure 3: Distribution of {len(df_auckland)} landslides within the Auckland region of New Zealand.", wrap=True, horizontalalignment='center', fontsize=10)
plt.savefig("auckland_landslide_map_static.png", dpi=600, bbox_inches='tight')
plt.close(fig_auckland) # Close the figure

print("Static Auckland landslide map saved as auckland_landslide_map_static.png")

"""## Summary

The analysis successfully loaded and processed the landslide data, generating static map visualizations for global distribution, all of New Zealand, and the Auckland region. The maps include the number of landslides in their captions and are saved as high-resolution PNG files suitable for publication.
"""